'use strict';
var app=angular.module('myApps',['ui.router','templates']);
app.config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){
	$urlRouterProvider.otherwise('/login');
	$stateProvider
		.state('login',{
			url:'/login',
			views:{
				'':{templateUrl:'component/login/login.html',controller:'loginCtrl'}
			}
		})
		.state('wpages',{
			url:'/wpages',
			views:{
				'':{templateUrl:'component/w/w.html'}
			}
		})
		.state('mpages',{
			url:'/mpages',
			views:{
				'':{templateUrl:'component/m/m.html'}
			}
		})
		.state('lpages',{
			url:'/lpages',
			views:{
				'':{templateUrl:'component/l/l.html'}
			}
		})
		.state('stage',{
			url:'/stage',
			views:{
				'':{
					templateUrl:'component/stage/stage.html',
					controller:'stageCtrl'
				}
			}
		})
		.state('backstage',{
			url:'/backstage',
			views:{
				'':{
					templateUrl:'template/backstage.html',
					controller:'backStageCtrl'
				},
				'viewContent@backstage':{
					templateUrl:'component/desktop/desktop.html',
					controller:'desktopCtrl'
				}
			}
		})
		.state('backage.desktop',{
			url:'/desktop',
			views:{
				'viewContent':{
					templateUrl:'component/desktop/desktop.html',
					controller:'desktopCtrl'
				}
			}
		})

}]);
angular.module('templates', []);